def additem_func(ui,solution):
    ui.lineEdit_1.setText (str(solution.matrix[0][0]))
    ui.lineEdit_2.setText (str(solution.matrix[0][1]))
    ui.lineEdit_3.setText (str(solution.matrix[0][2]))
    ui.lineEdit_4.setText (str(solution.matrix[0][3]))
    ui.lineEdit_5.setText (str(solution.matrix[0][4]))
    ui.lineEdit_6.setText (str(solution.matrix[0][5]))
    ui.lineEdit_7.setText (str(solution.matrix[0][6]))
    ui.lineEdit_8.setText (str(solution.matrix[0][7]))
    ui.lineEdit_9.setText (str(solution.matrix[0][8]))
    ui.lineEdit_10.setText(str(solution.matrix[1][0]))
    ui.lineEdit_11.setText(str(solution.matrix[1][1]))
    ui.lineEdit_12.setText(str(solution.matrix[1][2]))
    ui.lineEdit_13.setText(str(solution.matrix[1][3]))
    ui.lineEdit_14.setText(str(solution.matrix[1][4]))
    ui.lineEdit_15.setText(str(solution.matrix[1][5]))
    ui.lineEdit_16.setText(str(solution.matrix[1][6]))
    ui.lineEdit_17.setText(str(solution.matrix[1][7]))
    ui.lineEdit_18.setText(str(solution.matrix[1][8]))
    ui.lineEdit_19.setText(str(solution.matrix[2][0]))
    ui.lineEdit_20.setText(str(solution.matrix[2][1]))
    ui.lineEdit_21.setText(str(solution.matrix[2][2]))
    ui.lineEdit_22.setText(str(solution.matrix[2][3]))
    ui.lineEdit_23.setText(str(solution.matrix[2][4]))
    ui.lineEdit_24.setText(str(solution.matrix[2][5]))
    ui.lineEdit_25.setText(str(solution.matrix[2][6]))
    ui.lineEdit_26.setText(str(solution.matrix[2][7]))
    ui.lineEdit_27.setText(str(solution.matrix[2][8]))
    ui.lineEdit_28.setText(str(solution.matrix[3][0]))
    ui.lineEdit_29.setText(str(solution.matrix[3][1]))
    ui.lineEdit_30.setText(str(solution.matrix[3][2]))
    ui.lineEdit_31.setText(str(solution.matrix[3][3]))
    ui.lineEdit_32.setText(str(solution.matrix[3][4]))
    ui.lineEdit_33.setText(str(solution.matrix[3][5]))
    ui.lineEdit_34.setText(str(solution.matrix[3][6]))
    ui.lineEdit_35.setText(str(solution.matrix[3][7]))
    ui.lineEdit_36.setText(str(solution.matrix[3][8]))
    ui.lineEdit_37.setText(str(solution.matrix[4][0]))
    ui.lineEdit_38.setText(str(solution.matrix[4][1]))
    ui.lineEdit_39.setText(str(solution.matrix[4][2]))
    ui.lineEdit_40.setText(str(solution.matrix[4][3]))
    ui.lineEdit_41.setText(str(solution.matrix[4][4]))
    ui.lineEdit_42.setText(str(solution.matrix[4][5]))
    ui.lineEdit_43.setText(str(solution.matrix[4][6]))
    ui.lineEdit_44.setText(str(solution.matrix[4][7]))
    ui.lineEdit_45.setText(str(solution.matrix[4][8]))
    ui.lineEdit_46.setText(str(solution.matrix[5][0]))
    ui.lineEdit_47.setText(str(solution.matrix[5][1]))
    ui.lineEdit_48.setText(str(solution.matrix[5][2]))
    ui.lineEdit_49.setText(str(solution.matrix[5][3]))
    ui.lineEdit_50.setText(str(solution.matrix[5][4]))
    ui.lineEdit_51.setText(str(solution.matrix[5][5]))
    ui.lineEdit_52.setText(str(solution.matrix[5][6]))
    ui.lineEdit_53.setText(str(solution.matrix[5][7]))
    ui.lineEdit_54.setText(str(solution.matrix[5][8]))
    ui.lineEdit_55.setText(str(solution.matrix[6][0]))
    ui.lineEdit_56.setText(str(solution.matrix[6][1]))
    ui.lineEdit_57.setText(str(solution.matrix[6][2]))
    ui.lineEdit_58.setText(str(solution.matrix[6][3]))
    ui.lineEdit_59.setText(str(solution.matrix[6][4]))
    ui.lineEdit_60.setText(str(solution.matrix[6][5]))
    ui.lineEdit_61.setText(str(solution.matrix[6][6]))
    ui.lineEdit_62.setText(str(solution.matrix[6][7]))
    ui.lineEdit_63.setText(str(solution.matrix[6][8]))
    ui.lineEdit_64.setText(str(solution.matrix[7][0]))
    ui.lineEdit_65.setText(str(solution.matrix[7][1]))
    ui.lineEdit_66.setText(str(solution.matrix[7][2]))
    ui.lineEdit_67.setText(str(solution.matrix[7][3]))
    ui.lineEdit_68.setText(str(solution.matrix[7][4]))
    ui.lineEdit_69.setText(str(solution.matrix[7][5]))
    ui.lineEdit_70.setText(str(solution.matrix[7][6]))
    ui.lineEdit_71.setText(str(solution.matrix[7][7]))
    ui.lineEdit_72.setText(str(solution.matrix[7][8]))
    ui.lineEdit_73.setText(str(solution.matrix[8][0]))
    ui.lineEdit_74.setText(str(solution.matrix[8][1]))
    ui.lineEdit_75.setText(str(solution.matrix[8][2]))
    ui.lineEdit_76.setText(str(solution.matrix[8][3]))
    ui.lineEdit_77.setText(str(solution.matrix[8][4]))
    ui.lineEdit_78.setText(str(solution.matrix[8][5]))
    ui.lineEdit_79.setText(str(solution.matrix[8][6]))
    ui.lineEdit_80.setText(str(solution.matrix[8][7]))
    ui.lineEdit_81.setText(str(solution.matrix[8][8]))