
def reset_func(ui):
    ui.lineEdit_1.setText ("")
    ui.lineEdit_2.setText ("")
    ui.lineEdit_3.setText ("")
    ui.lineEdit_4.setText ("")
    ui.lineEdit_5.setText ("")
    ui.lineEdit_6.setText ("")
    ui.lineEdit_7.setText ("")
    ui.lineEdit_8.setText ("")
    ui.lineEdit_9.setText ("")
    ui.lineEdit_10.setText("")
    ui.lineEdit_11.setText("")
    ui.lineEdit_12.setText("")
    ui.lineEdit_13.setText("")
    ui.lineEdit_14.setText("")
    ui.lineEdit_15.setText("")
    ui.lineEdit_16.setText("")
    ui.lineEdit_17.setText("")
    ui.lineEdit_18.setText("")
    ui.lineEdit_19.setText("")
    ui.lineEdit_20.setText("")
    ui.lineEdit_21.setText("")
    ui.lineEdit_22.setText("")
    ui.lineEdit_23.setText("")
    ui.lineEdit_24.setText("")
    ui.lineEdit_25.setText("")
    ui.lineEdit_26.setText("")
    ui.lineEdit_27.setText("")
    ui.lineEdit_28.setText("")
    ui.lineEdit_29.setText("")
    ui.lineEdit_30.setText("")
    ui.lineEdit_31.setText("")
    ui.lineEdit_32.setText("")
    ui.lineEdit_33.setText("")
    ui.lineEdit_34.setText("")
    ui.lineEdit_35.setText("")
    ui.lineEdit_36.setText("")
    ui.lineEdit_37.setText("")
    ui.lineEdit_38.setText("")
    ui.lineEdit_39.setText("")
    ui.lineEdit_40.setText("")
    ui.lineEdit_41.setText("")
    ui.lineEdit_42.setText("")
    ui.lineEdit_43.setText("")
    ui.lineEdit_44.setText("")
    ui.lineEdit_45.setText("")
    ui.lineEdit_46.setText("")
    ui.lineEdit_47.setText("")
    ui.lineEdit_48.setText("")
    ui.lineEdit_49.setText("")
    ui.lineEdit_50.setText("")
    ui.lineEdit_51.setText("")
    ui.lineEdit_52.setText("")
    ui.lineEdit_53.setText("")
    ui.lineEdit_54.setText("")
    ui.lineEdit_55.setText("")
    ui.lineEdit_56.setText("")
    ui.lineEdit_57.setText("")
    ui.lineEdit_58.setText("")
    ui.lineEdit_59.setText("")
    ui.lineEdit_60.setText("")
    ui.lineEdit_61.setText("")
    ui.lineEdit_62.setText("")
    ui.lineEdit_63.setText("")
    ui.lineEdit_64.setText("")
    ui.lineEdit_65.setText("")
    ui.lineEdit_66.setText("")
    ui.lineEdit_67.setText("")
    ui.lineEdit_68.setText("")
    ui.lineEdit_69.setText("")
    ui.lineEdit_70.setText("")
    ui.lineEdit_71.setText("")
    ui.lineEdit_72.setText("")
    ui.lineEdit_73.setText("")
    ui.lineEdit_74.setText("")
    ui.lineEdit_75.setText("")
    ui.lineEdit_76.setText("")
    ui.lineEdit_77.setText("")
    ui.lineEdit_78.setText("")
    ui.lineEdit_79.setText("")
    ui.lineEdit_80.setText("")
    ui.lineEdit_81.setText("")
