# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget,QLabel
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QMovie

class Ui_MainWindow(object):
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 620)
        MainWindow.setMinimumSize(QtCore.QSize(522, 620))
        MainWindow.setMaximumSize(QtCore.QSize(522, 620))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(25)
        font.setItalic(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:#32de84;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(30, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setMouseTracking(False)
        self.lineEdit_1.setStyleSheet("background-color:#8FBC8B;")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.lineEdit_2.setMouseTracking(False)
        self.lineEdit_2.setStyleSheet("background-color:#8FBC8B;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setMouseTracking(False)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setMouseTracking(False)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setMouseTracking(False)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(290, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setMouseTracking(False)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(350, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setMouseTracking(False)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(400, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setMouseTracking(False)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(450, 30, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setMouseTracking(False)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(30, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setMouseTracking(False)
        self.lineEdit_10.setStyleSheet("background-color:#8FBC8B;")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(80, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setMouseTracking(False)
        self.lineEdit_11.setStyleSheet("background-color:#8FBC8B;")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(130, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setMouseTracking(False)
        self.lineEdit_12.setStyleSheet("background-color:#8FBC8B;")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(190, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setMouseTracking(False)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(240, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setMouseTracking(False)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(290, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setMouseTracking(False)
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(350, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setMouseTracking(False)
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(400, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setMouseTracking(False)
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(450, 80, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setMouseTracking(False)
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(30, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setMouseTracking(False)
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(80, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setMouseTracking(False)
        self.lineEdit_20.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(130, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setMouseTracking(False)
        self.lineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(190, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setMouseTracking(False)
        self.lineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(240, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setMouseTracking(False)
        self.lineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(290, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setMouseTracking(False)
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(350, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setMouseTracking(False)
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(400, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setMouseTracking(False)
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(450, 130, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setMouseTracking(False)
        self.lineEdit_27.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(30, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setMouseTracking(False)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(80, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setMouseTracking(False)
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(130, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setMouseTracking(False)
        self.lineEdit_30.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(190, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setMouseTracking(False)
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(240, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setMouseTracking(False)
        self.lineEdit_32.setStyleSheet("background-color:#8FBC8B;")
        self.lineEdit_32.setText("")
        self.lineEdit_32.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(290, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setMouseTracking(False)
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(350, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setMouseTracking(False)
        self.lineEdit_34.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(400, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setMouseTracking(False)
        self.lineEdit_35.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_36.setGeometry(QtCore.QRect(450, 190, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setMouseTracking(False)
        self.lineEdit_36.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_37.setGeometry(QtCore.QRect(30, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setMouseTracking(False)
        self.lineEdit_37.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_38.setGeometry(QtCore.QRect(80, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setMouseTracking(False)
        self.lineEdit_38.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_39.setGeometry(QtCore.QRect(130, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_39.setFont(font)
        self.lineEdit_39.setMouseTracking(False)
        self.lineEdit_39.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_40.setGeometry(QtCore.QRect(190, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_40.setFont(font)
        self.lineEdit_40.setMouseTracking(False)
        self.lineEdit_40.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_41.setGeometry(QtCore.QRect(240, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_41.setFont(font)
        self.lineEdit_41.setMouseTracking(False)
        self.lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_42.setGeometry(QtCore.QRect(290, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_42.setFont(font)
        self.lineEdit_42.setMouseTracking(False)
        self.lineEdit_42.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_43.setGeometry(QtCore.QRect(350, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setMouseTracking(False)
        self.lineEdit_43.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_44.setGeometry(QtCore.QRect(400, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_44.setFont(font)
        self.lineEdit_44.setMouseTracking(False)
        self.lineEdit_44.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_45.setGeometry(QtCore.QRect(450, 240, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_45.setFont(font)
        self.lineEdit_45.setMouseTracking(False)
        self.lineEdit_45.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_46.setGeometry(QtCore.QRect(30, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_46.setFont(font)
        self.lineEdit_46.setMouseTracking(False)
        self.lineEdit_46.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_47.setGeometry(QtCore.QRect(80, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_47.setFont(font)
        self.lineEdit_47.setMouseTracking(False)
        self.lineEdit_47.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_48.setGeometry(QtCore.QRect(130, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_48.setFont(font)
        self.lineEdit_48.setMouseTracking(False)
        self.lineEdit_48.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_49.setGeometry(QtCore.QRect(190, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_49.setFont(font)
        self.lineEdit_49.setMouseTracking(False)
        self.lineEdit_49.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_50.setGeometry(QtCore.QRect(240, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_50.setFont(font)
        self.lineEdit_50.setMouseTracking(False)
        self.lineEdit_50.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_51.setGeometry(QtCore.QRect(290, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_51.setFont(font)
        self.lineEdit_51.setMouseTracking(False)
        self.lineEdit_51.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_52.setGeometry(QtCore.QRect(350, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_52.setFont(font)
        self.lineEdit_52.setMouseTracking(False)
        self.lineEdit_52.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_53.setGeometry(QtCore.QRect(400, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_53.setFont(font)
        self.lineEdit_53.setMouseTracking(False)
        self.lineEdit_53.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_54.setGeometry(QtCore.QRect(450, 290, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_54.setFont(font)
        self.lineEdit_54.setMouseTracking(False)
        self.lineEdit_54.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_55.setGeometry(QtCore.QRect(30, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_55.setFont(font)
        self.lineEdit_55.setMouseTracking(False)
        self.lineEdit_55.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_56.setGeometry(QtCore.QRect(80, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_56.setFont(font)
        self.lineEdit_56.setMouseTracking(False)
        self.lineEdit_56.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_57.setGeometry(QtCore.QRect(130, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_57.setFont(font)
        self.lineEdit_57.setMouseTracking(False)
        self.lineEdit_57.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_58.setGeometry(QtCore.QRect(190, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_58.setFont(font)
        self.lineEdit_58.setMouseTracking(False)
        self.lineEdit_58.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_59.setGeometry(QtCore.QRect(240, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_59.setFont(font)
        self.lineEdit_59.setMouseTracking(False)
        self.lineEdit_59.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_60.setGeometry(QtCore.QRect(290, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_60.setFont(font)
        self.lineEdit_60.setMouseTracking(False)
        self.lineEdit_60.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_61.setGeometry(QtCore.QRect(350, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_61.setFont(font)
        self.lineEdit_61.setMouseTracking(False)
        self.lineEdit_61.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_62.setGeometry(QtCore.QRect(400, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_62.setFont(font)
        self.lineEdit_62.setMouseTracking(False)
        self.lineEdit_62.setText("")
        self.lineEdit_62.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_63.setGeometry(QtCore.QRect(450, 350, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_63.setFont(font)
        self.lineEdit_63.setMouseTracking(False)
        self.lineEdit_63.setText("")
        self.lineEdit_63.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_64.setGeometry(QtCore.QRect(30, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_64.setFont(font)
        self.lineEdit_64.setMouseTracking(False)
        self.lineEdit_64.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_65.setGeometry(QtCore.QRect(80, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_65.setFont(font)
        self.lineEdit_65.setMouseTracking(False)
        self.lineEdit_65.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_66.setGeometry(QtCore.QRect(130, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_66.setFont(font)
        self.lineEdit_66.setMouseTracking(False)
        self.lineEdit_66.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_67.setGeometry(QtCore.QRect(190, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_67.setFont(font)
        self.lineEdit_67.setMouseTracking(False)
        self.lineEdit_67.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.lineEdit_68 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_68.setGeometry(QtCore.QRect(240, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_68.setFont(font)
        self.lineEdit_68.setMouseTracking(False)
        self.lineEdit_68.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.lineEdit_69 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_69.setGeometry(QtCore.QRect(290, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_69.setFont(font)
        self.lineEdit_69.setMouseTracking(False)
        self.lineEdit_69.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.lineEdit_70 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_70.setGeometry(QtCore.QRect(350, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_70.setFont(font)
        self.lineEdit_70.setMouseTracking(False)
        self.lineEdit_70.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.lineEdit_71 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_71.setGeometry(QtCore.QRect(400, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_71.setFont(font)
        self.lineEdit_71.setMouseTracking(False)
        self.lineEdit_71.setText("")
        self.lineEdit_71.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.lineEdit_72 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_72.setGeometry(QtCore.QRect(450, 400, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_72.setFont(font)
        self.lineEdit_72.setMouseTracking(False)
        self.lineEdit_72.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.lineEdit_73 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_73.setGeometry(QtCore.QRect(30, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_73.setFont(font)
        self.lineEdit_73.setMouseTracking(False)
        self.lineEdit_73.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.lineEdit_74 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_74.setGeometry(QtCore.QRect(80, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_74.setFont(font)
        self.lineEdit_74.setMouseTracking(False)
        self.lineEdit_74.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.lineEdit_75 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_75.setGeometry(QtCore.QRect(130, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_75.setFont(font)
        self.lineEdit_75.setMouseTracking(False)
        self.lineEdit_75.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.lineEdit_76 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_76.setGeometry(QtCore.QRect(190, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_76.setFont(font)
        self.lineEdit_76.setMouseTracking(False)
        self.lineEdit_76.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.lineEdit_77 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_77.setGeometry(QtCore.QRect(240, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_77.setFont(font)
        self.lineEdit_77.setMouseTracking(False)
        self.lineEdit_77.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.lineEdit_78 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_78.setGeometry(QtCore.QRect(290, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_78.setFont(font)
        self.lineEdit_78.setMouseTracking(False)
        self.lineEdit_78.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.lineEdit_79 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_79.setGeometry(QtCore.QRect(350, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_79.setFont(font)
        self.lineEdit_79.setMouseTracking(False)
        self.lineEdit_79.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.lineEdit_80 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_80.setGeometry(QtCore.QRect(400, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_80.setFont(font)
        self.lineEdit_80.setMouseTracking(False)
        self.lineEdit_80.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.lineEdit_81 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_81.setGeometry(QtCore.QRect(450, 450, 40, 40))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_81.setFont(font)
        self.lineEdit_81.setMouseTracking(False)
        self.lineEdit_81.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setGeometry(QtCore.QRect(20, 20, 480, 1))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.line_1.setFont(font)
        self.line_1.setMouseTracking(False)
        self.line_1.setStyleSheet("background-color:#00853E;")
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 180, 480, 1))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setMouseTracking(False)
        self.line_2.setStyleSheet("background-color:#00853E;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(20, 340, 480, 1))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_3.setFont(font)
        self.line_3.setMouseTracking(False)
        self.line_3.setStyleSheet("background-color:#00853E;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(20, 500, 480, 1))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.line_4.setFont(font)
        self.line_4.setMouseTracking(False)
        self.line_4.setStyleSheet("background-color:#00853E;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(20, 20, 1, 480))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.line_5.setFont(font)
        self.line_5.setMouseTracking(False)
        self.line_5.setStyleSheet("background-color:#00853E;")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(180, 20, 1, 480))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_6.setFont(font)
        self.line_6.setMouseTracking(False)
        self.line_6.setStyleSheet("background-color:#00853E;")
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(340, 20, 1, 480))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_7.setFont(font)
        self.line_7.setMouseTracking(False)
        self.line_7.setStyleSheet("background-color:#00853E;")
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(500, 20, 1, 480))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.line_8.setFont(font)
        self.line_8.setMouseTracking(False)
        self.line_8.setStyleSheet("background-color:#00853E;")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.Button = QtWidgets.QPushButton(self.centralwidget)
        self.Button.setGeometry(QtCore.QRect(190, 510, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Button.setFont(font)
        self.Button.setMouseTracking(False)
        self.Button.setStyleSheet("background-color:#E25822;")
        self.Button.setObjectName("Button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 570, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_2.setGeometry(QtCore.QRect(420, 540, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Button_2.setFont(font)
        self.Button_2.setMouseTracking(False)
        self.Button_2.setStyleSheet("background-color:#E25822;")
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(420, 510, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Z003")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Button_3.setFont(font)
        self.Button_3.setMouseTracking(False)
        self.Button_3.setStyleSheet("background-color:#E25822;")
        self.Button_3.setObjectName("Button_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku Solver"))
        self.lineEdit_3.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_4.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_5.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_6.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_7.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_8.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_9.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_13.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_14.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_15.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_16.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_17.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_18.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_19.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_20.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_21.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_22.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_23.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_24.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_25.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_26.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_27.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_28.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_29.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_30.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_31.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_33.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_34.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_35.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_36.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_37.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_38.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_39.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_40.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_41.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_42.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_43.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_44.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_45.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_46.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_47.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_48.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_49.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_50.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_51.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_52.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_53.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_54.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_55.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_56.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_57.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_58.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_59.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_60.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_61.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_62.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_63.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_64.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_65.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_66.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_67.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_68.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_69.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_70.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_71.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_72.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_73.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_74.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_75.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_76.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_77.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_78.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_79.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_80.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.lineEdit_81.setStyleSheet(_translate("MainWindow", "background-color:#8FBC8B;"))
        self.Button.setText(_translate("MainWindow", "SOLVE !"))
        self.label.setText(_translate("MainWindow", "Created by Enes Karacabay"))
        self.Button_2.setText(_translate("MainWindow", "RESET"))
        self.Button_3.setText(_translate("MainWindow", "OPEN"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
